name: Vercel Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.wgmD5gsLwWiITc59zv33Sqij }}
  VERCEL_PROJECT_ID: ${{ secrets.prj_k7rtu0OkZZWr5Q1WeQdl97GUKAQ3 }}
on:
  push:
    branches-ignore:
      - main
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.kn94W93DLpMoCfvliOKmC8yU }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.kn94W93DLpMoCfvliOKmC8yU }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.kn94W93DLpMoCfvliOKmC8yU }}
